spring:
     
  banner:
    location: classpath:banner/banner.txt
    image:
     location: classpath:fotocreador/nttdata2.PNG


  application:
    name: config-server
  cloud:
    config:
      server:
        bootstrap: false
        git:
          clone-on-start: true
          uri: https://alucardaywalker@bitbucket.org/alucardaywalker/config-repo.git
          default-label: master
          username: alucardaywalker
          password: 1983joffre

          
          
